version: 0.2
env:
    variables:
        JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
phases:
    install:
        runtime-versions:
            java: openjdk8
    commands:
        - echo Installing maven..
        - apt-get update -y
        - apt-get install -y maven
    build:
        commands:
            - echo Building..
            - mvn install
artifacts:
    files:
        - target/*.jar
    discard-paths: yes
cache:
    paths:
        - '/root/.m2/**/*'